syntax = "proto3";

package xray.transport.internet;
option csharp_namespace = "Xray.Transport.Internet";
option go_package = "github.com/xtls/xray-core/transport/internet";
option java_package = "com.xray.transport.internet";
option java_multiple_files = true;

import "common/serial/typed_message.proto";
import "common/net/address.proto";
import "transport/internet/socket/config.proto";

message TransportConfig {
  // Transport protocol name.
  string protocol_name = 3;

  // Specific transport protocol settings.
  xray.common.serial.TypedMessage settings = 2;
}

message StreamConfig {
  xray.common.net.IPOrDomain address = 8;
  uint32 port = 9;

  // Effective network.
  string protocol_name = 5;

  repeated TransportConfig transport_settings = 2;

  // Type of security. Must be a message name of the settings proto.
  string security_type = 3;

  // Transport security settings. They can be either TLS or REALITY.
  repeated xray.common.serial.TypedMessage security_settings = 4;

  repeated xray.common.serial.TypedMessage udpmasks = 10;
  repeated xray.common.serial.TypedMessage tcpmasks = 11;

  QuicParams quic_params = 12;

  xray.transport.internet.socket.SocketConfig socket_settings = 6;
}

message UdpHop {
  repeated uint32 ports = 1;
  int64 interval_min = 2;
  int64 interval_max = 3;
}

message QuicParams {
  string congestion = 1;
  string bbr_profile = 2;
  uint64 brutal_up = 3;
  uint64 brutal_down = 4;
  UdpHop udp_hop = 5;
  uint64 init_stream_receive_window = 6;
  uint64 max_stream_receive_window = 7;
  uint64 init_conn_receive_window = 8;
  uint64 max_conn_receive_window = 9;
  int64 max_idle_timeout = 10;
  int64 keep_alive_period = 11;
  bool disable_path_mtu_discovery = 12;
  int64 max_incoming_streams = 13;
}

message ProxyConfig {
  string tag = 1;
  bool transportLayerProxy = 2;
}
